In [1]:
%cd ..

/app


In [2]:
import gym 
import numpy as np
from tqdm import tqdm

from tensoraerospace.envs import LinearLongitudinalX15
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step

In [3]:
dt = 0.01  # Дискретизация
tp = generate_time_period(tn=20, dt=dt) # Временной периуд
tps = convert_tp_to_sec_tp(tp, dt=dt)
number_time_steps = len(tp) # Количество временных шагов
reference_signals = np.reshape(unit_step(degree=5, tp=tp, time_step=10, output_rad=True), [1, -1]) # Заданный сигнал

In [4]:
env = gym.make('LinearLongitudinalX15-v0',
               number_time_steps=number_time_steps, 
               initial_state=[[0],[0],[0],[0]],
               reference_signal = reference_signals)
env.reset()

In [5]:
observation, reward, done, info = env.step(np.array([[1]]))

In [6]:
env.model.store_input

array([[1., 0., 0., ..., 0., 0., 0.]])

In [7]:
observation

array([[-5.91396593e-09],
       [-1.16165197e-06]])

In [8]:
reward

array([5.91396593e-09])