In [1]:
%cd ..

/app


In [1]:
import gymnasium as gym 
import numpy as np
from tqdm import tqdm

from tensoraerospace.envs import LinearLongitudinalF16
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step
from tensoraerospace.agent.ihdp.model import IHDPAgent

In [2]:
dt = 0.01  # Дискретизация
tp = generate_time_period(tn=20, dt=dt) # Временной периуд
tps = convert_tp_to_sec_tp(tp, dt=dt)
number_time_steps = len(tp) # Количество временных шагов
reference_signals = np.reshape(unit_step(degree=5, tp=tp, time_step=10, output_rad=True), [1, -1]) # Заданный сигнал

In [3]:
env = gym.make('LinearLongitudinalF16-v0',
               number_time_steps=number_time_steps, 
               initial_state=[[0],[0],[0],[0]],
               reference_signal = reference_signals)
env.reset()

(array([[0.],
        [0.]]),
 {})

In [5]:
observation, reward, terminated, truncated, info = env.step(np.array([[1]]))

In [6]:
observation

array([[-3.25488004e-05],
       [-1.13115739e-03]])

In [8]:
reward

array([3.25488004e-05])