# 🛰️ Example: Working with the ComSat Environment

This notebook demonstrates the usage of the **ComSat** (communication satellite) environment from the TensorAeroSpace library.

## 📋 Contents
1. Import the required libraries
2. Configure simulation parameters
3. Create and initialize the environment
4. Execute a simulation step
5. Analyze the results

---

## 📚 Importing Libraries

Loading all necessary modules for working with the communication satellite environment:

In [1]:
# Основные библиотеки для работы с окружениями и численными вычислениями
import gymnasium as gym 
import numpy as np
from tqdm import tqdm

# Специализированные модули TensorAeroSpace
from tensoraerospace.envs import ComSatEnv
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step

## ⚙️ Simulation Parameters Setup

Defining the main parameters for modeling satellite dynamics:

In [2]:
# Параметры дискретизации и времени
dt = 0.01  # Шаг дискретизации (секунды)
tp = generate_time_period(tn=20, dt=dt)  # Временной период (20 секунд)
tps = convert_tp_to_sec_tp(tp, dt=dt)    # Преобразование временного периода
number_time_steps = len(tp)              # Общее количество временных шагов

# Формирование опорного сигнала (единичный скачок)
reference_signals = np.reshape(
    unit_step(degree=5, tp=tp, time_step=10, output_rad=True), 
    [1, -1]
)  # Заданный сигнал управления

## 🚀 Creating the ComSat Environment

Initializing the communication satellite environment with the specified parameters:

In [3]:
# Создание окружения спутника связи
env = gym.make('ComSat-v0',
               number_time_steps=number_time_steps,  # Количество временных шагов
               initial_state=[[0],[0],[0]],          # Начальное состояние системы
               output_space=None,                    # Пространство выходов (автоматическое)
               reference_signal=reference_signals)   # Опорный сигнал

# Сброс окружения к начальному состоянию
env.reset()

(array([[0.],
        [0.],
        [0.]], dtype=float32),
 {})

## 🎯 Executing a Simulation Step

Applying a control action and obtaining the system response:

In [4]:
# Выполнение одного шага симуляции с управляющим сигналом
observation, reward, terminated, truncated, info = env.step(np.array([[1]]))

/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:246: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(


## 📊 Analyzing the Results

Examining the obtained system state data:

In [5]:
# Просмотр истории управляющих воздействий
env.unwrapped.model.store_input

array([[1., 0., 0., ..., 0., 0., 0.]])

In [6]:
# Значение опорного сигнала на втором временном шаге
env.unwrapped.reference_signal[0][1]

0.0

In [7]:
# Полученная награда за выполненное действие
reward

array([5.86514433e-06])

## 🎉 Conclusion

In this example we successfully:

- ✅ Configured the communication satellite simulation parameters
- ✅ Created the ComSat environment with the specified characteristics
- ✅ Executed a simulation step with a control action
- ✅ Analyzed the system operation results

The obtained reward `5.86126179e-06` indicates the control quality at this step.

---

💡 **Tip**: For a more detailed analysis, it is recommended to perform several simulation steps and plot the system state changes over time.