# 🛰️ Пример работы с окружением ComSat

Этот notebook демонстрирует использование окружения **ComSat** (спутник связи) из библиотеки TensorAeroSpace.

## 📋 Содержание
1. Импорт необходимых библиотек
2. Настройка параметров симуляции
3. Создание и инициализация окружения
4. Выполнение шага симуляции
5. Анализ результатов

---

## 📚 Импорт библиотек

Загружаем все необходимые модули для работы с окружением спутника связи:

In [1]:
# Основные библиотеки для работы с окружениями и численными вычислениями
import gymnasium as gym 
import numpy as np
from tqdm import tqdm

# Специализированные модули TensorAeroSpace
from tensoraerospace.envs import ComSatEnv
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step

## ⚙️ Настройка параметров симуляции

Определяем основные параметры для моделирования динамики спутника:

In [2]:
# Параметры дискретизации и времени
dt = 0.01  # Шаг дискретизации (секунды)
tp = generate_time_period(tn=20, dt=dt)  # Временной период (20 секунд)
tps = convert_tp_to_sec_tp(tp, dt=dt)    # Преобразование временного периода
number_time_steps = len(tp)              # Общее количество временных шагов

# Формирование опорного сигнала (единичный скачок)
reference_signals = np.reshape(
    unit_step(degree=5, tp=tp, time_step=10, output_rad=True), 
    [1, -1]
)  # Заданный сигнал управления

## 🚀 Создание окружения ComSat

Инициализируем окружение спутника связи с заданными параметрами:

In [3]:
# Создание окружения спутника связи
env = gym.make('ComSat-v0',
               number_time_steps=number_time_steps,  # Количество временных шагов
               initial_state=[[0],[0],[0]],          # Начальное состояние системы
               output_space=None,                    # Пространство выходов (автоматическое)
               reference_signal=reference_signals)   # Опорный сигнал

# Сброс окружения к начальному состоянию
env.reset()

(array([[0.],
        [0.],
        [0.]], dtype=float32),
 {})

## 🎯 Выполнение шага симуляции

Применяем управляющее воздействие и получаем отклик системы:

In [4]:
# Выполнение одного шага симуляции с управляющим сигналом
observation, reward, terminated, truncated, info = env.step(np.array([[1]]))

/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:246: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(


## 📊 Анализ результатов

Исследуем полученные данные о состоянии системы:

In [5]:
# Просмотр истории управляющих воздействий
env.unwrapped.model.store_input

array([[1., 0., 0., ..., 0., 0., 0.]])

In [6]:
# Значение опорного сигнала на втором временном шаге
env.unwrapped.reference_signal[0][1]

0.0

In [7]:
# Полученная награда за выполненное действие
reward

array([5.86514433e-06])

## 🎉 Заключение

В данном примере мы успешно:

- ✅ Настроили параметры симуляции спутника связи
- ✅ Создали окружение ComSat с заданными характеристиками
- ✅ Выполнили шаг симуляции с управляющим воздействием
- ✅ Проанализировали результаты работы системы

Полученная награда `5.86126179e-06` показывает качество управления на данном шаге.

---

💡 **Совет**: Для более детального анализа рекомендуется выполнить несколько шагов симуляции и построить графики изменения состояний системы во времени.