# 🚀 Example: Using LinearLongitudinalF16

This notebook demonstrates working with the longitudinal dynamic model of the F-16 aircraft in the TensorAeroSpace library.

## 📋 What we will learn:
- Creating and configuring the F-16 environment
- Generating reference signals
- Executing simulation steps
- Analyzing results

---

## 📦 Importing Required Libraries

Loading all necessary modules for working with the F-16 model:

In [1]:
# Основные библиотеки
import gymnasium as gym 
import numpy as np

# Импорт TensorAeroSpace для регистрации окружений
import tensoraerospace

# Модули TensorAeroSpace
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step

## ⚙️ Simulation Parameters Setup

Defining time parameters and creating a reference signal for pitch angle control:

In [2]:
# Параметры времени
dt = 0.01  # Шаг дискретизации (секунды)
tp = generate_time_period(tn=20, dt=dt)  # Временной период 20 секунд
tps = convert_tp_to_sec_tp(tp, dt=dt)  # Преобразование в секунды
number_time_steps = len(tp)  # Общее количество временных шагов

# Создание опорного сигнала для отслеживания угла тангажа (theta)
# Формат: (num_tracking_states, number_time_steps)
# По умолчанию tracking_states = ["alpha", "q"], но мы будем использовать ["theta"]
reference_signals = unit_step(degree=5, tp=tp, time_step=10, output_rad=True)
reference_signals = np.reshape(reference_signals, [1, -1])  # Формат: [1, время] для отслеживания theta

print(f'📊 Параметры симуляции:')
print(f'   • Шаг времени: {dt} сек')
print(f'   • Общее время: {tps[-1]:.1f} сек')
print(f'   • Количество шагов: {number_time_steps}')
print(f'   • Размер опорного сигнала: {reference_signals.shape}')

📊 Параметры симуляции:
   • Шаг времени: 0.01 сек
   • Общее время: 20.0 сек
   • Количество шагов: 2002
   • Размер опорного сигнала: (1, 2002)


## 🛩️ Creating the F-16 Environment

Creating the F-16 longitudinal dynamics environment. The model supports the following states:
- **theta** - pitch angle [rad]
- **alpha** - angle of attack [rad]
- **q** - pitch rate [rad/s]

**Important:** The linear F-16 model does not include altitude and velocity as separate states.
By default the states `["alpha", "q"]` are used, but we can use `["theta", "q"]` or `["theta", "alpha", "q"]`.

In [3]:
# Создание среды F-16
# Используем состояния theta и q (как в тестах)
# По умолчанию: state_space=["alpha", "q"], tracking_states=["alpha", "q"]
env = gym.make('LinearLongitudinalF16-v0',
                number_time_steps=number_time_steps,  # Количество временных шагов
                initial_state=[[0], [0]],             # Начальное состояние [theta, q] в радианах
                reference_signal=reference_signals,   # Опорный сигнал для theta
                state_space=["theta", "q"],            # Пространство состояний
                output_space=["theta", "q"],          # Выходное пространство
                tracking_states=["theta"],            # Отслеживаемые состояния (theta)
                use_reward=True)                      # Использовать функцию награды

# Инициализация среды
initial_observation, info = env.reset()
print(f'✅ Среда F-16 успешно создана!')
print(f'📏 Размер начального наблюдения: {initial_observation.shape}')
print(f'🎯 Форма пространства состояний: {env.observation_space.shape}')
print(f'🎮 Форма пространства действий: {env.action_space.shape}')
print(f'📊 Отслеживаемые состояния: {env.unwrapped.tracking_states}')
print(f'📋 Пространство состояний: {env.unwrapped.state_space}')
print(f'📤 Пространство выходов: {env.unwrapped.output_space}')
initial_observation, info

✅ Среда F-16 успешно создана!
📏 Размер начального наблюдения: (2, 1)
🎯 Форма пространства состояний: (2, 1)
🎮 Форма пространства действий: (1, 1)
📊 Отслеживаемые состояния: ['theta']
📋 Пространство состояний: ['theta', 'q']
📤 Пространство выходов: ['theta', 'q']


(array([[0.],
        [0.]], dtype=float32),
 {})

## 🎮 Executing a Simulation Step

Applying a control action (elevator deflection) and observing the system response:

In [4]:
# Применение управляющего воздействия
# Действие должно быть в радианах (отклонение руля высоты)
# Диапазон действия: [-0.5, 0.5] радиан (примерно [-28.6, 28.6] градусов)
# Внутри среды действия ограничиваются до [-25, 25] градусов
control_action = np.array([0.1], dtype=np.float32)  # 0.1 радиан ≈ 5.7 градусов

# Выполнение одного шага симуляции
observation, reward, terminated, truncated, info = env.step(control_action)

print(f'🎯 Управляющее воздействие: {control_action[0]:.4f} рад ({np.rad2deg(control_action[0]):.2f} град)')
print(f'📊 Новое состояние: {observation.flatten()}')
print(f'   • Угол тангажа (theta): {observation[0, 0]:.6f} рад ({np.rad2deg(observation[0, 0]):.4f} град)')
print(f'   • Угловая скорость (q): {observation[1, 0]:.6f} рад/с ({np.rad2deg(observation[1, 0]):.4f} град/с)')
print(f'🏆 Награда: {reward}')
print(f'🔚 Завершено: {terminated}')
print(f'⏰ Прервано по времени: {truncated}')

🎯 Управляющее воздействие: 0.1000 рад (5.73 град)
📊 Новое состояние: [-2.84313825e-07 -5.67862026e-05]
   • Угол тангажа (theta): -0.000000 рад (-0.0000 град)
   • Угловая скорость (q): -0.000057 рад/с (-0.0033 град/с)
🏆 Награда: [-5.96293409e-06]
🔚 Завершено: False
⏰ Прервано по времени: False


/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:246: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(


## 📊 Analyzing the Results

Examining the observations and rewards obtained after the step:

In [5]:
# Текущее состояние системы после применения управления
print('🔍 Состояние системы F-16:')
print(f'   • Угол тангажа (theta): {observation[0, 0]:.6f} рад ({np.rad2deg(observation[0, 0]):.4f} град)')
print(f'   • Угловая скорость тангажа (q): {observation[1, 0]:.6f} рад/с ({np.rad2deg(observation[1, 0]):.4f} град/с)')
print(f'\n📐 Форма наблюдения: {observation.shape}')
print(f'   • Ожидаемая форма: ({len(env.unwrapped.state_space)}, 1)')

observation

🔍 Состояние системы F-16:
   • Угол тангажа (theta): -0.000000 рад (-0.0000 град)
   • Угловая скорость тангажа (q): -0.000057 рад/с (-0.0033 град/с)

📐 Форма наблюдения: (2, 1)
   • Ожидаемая форма: (2, 1)


array([[-2.84313825e-07],
       [-5.67862026e-05]])

### 🎯 Reward Analysis

Evaluating the control quality through the obtained reward:

In [6]:
# Анализ полученной награды
print('🎯 Анализ награды:')
print(f'   • Текущая награда: {reward}')

# Награда может быть numpy array или float
if isinstance(reward, np.ndarray):
    reward_value = reward.item() if reward.size == 1 else reward[0]
else:
    reward_value = reward

if reward_value >= 0:
    print('   ✅ Положительная награда - хорошее управление!')
elif reward_value < 0:
    print('   ⚠️  Отрицательная награда - требуется улучшение управления')

print('\n📈 Интерпретация функции награды:')
print('   • Награда = -|theta - theta_ref| - 0.1 * |q|')
print('   • Отражает качество отслеживания опорного сигнала (theta)')
print('   • Штрафует за высокую угловую скорость (q)')
print('   • Чем ближе к нулю (или выше), тем лучше управление')

reward

🎯 Анализ награды:
   • Текущая награда: [-5.96293409e-06]
   ⚠️  Отрицательная награда - требуется улучшение управления

📈 Интерпретация функции награды:
   • Награда = -|theta - theta_ref| - 0.1 * |q|
   • Отражает качество отслеживания опорного сигнала (theta)
   • Штрафует за высокую угловую скорость (q)
   • Чем ближе к нулю (или выше), тем лучше управление


array([-5.96293409e-06])

### 🏁 Episode Termination

Checking the simulation termination status:

## 🔄 Full Simulation

Running a full simulation over several steps to demonstrate the environment:


In [7]:
# Сброс среды для новой симуляции
state, info = env.reset()

# Хранение истории для визуализации
states_history = []
rewards_history = []
actions_history = []

# Выполнение симуляции на 500 шагов
num_simulation_steps = 500
for step in range(num_simulation_steps):
    # Простое управление: пропорциональное управление по ошибке
    # Получаем текущий опорный сигнал
    ref_idx = min(step, env.unwrapped.reference_signal.shape[1] - 1)
    target_theta = env.unwrapped.reference_signal[0, ref_idx]
    
    # Текущий угол тангажа (в радианах)
    current_theta = state[env.unwrapped.state_space.index("theta"), 0]
    
    # Пропорциональное управление
    error = target_theta - current_theta
    action = np.array([np.clip(error * 2.0, -0.5, 0.5)], dtype=np.float32)
    
    # Выполнение шага
    state, reward, terminated, truncated, info = env.step(action)
    
    # Сохранение истории
    states_history.append(state.copy())
    rewards_history.append(reward.item() if isinstance(reward, np.ndarray) else reward)
    actions_history.append(action[0])
    
    # Проверка завершения
    if terminated or truncated:
        print(f'Симуляция завершена на шаге {step + 1}')
        break

print(f'✅ Симуляция завершена!')
print(f'   • Выполнено шагов: {len(states_history)}')
print(f'   • Средняя награда: {np.mean(rewards_history):.6f}')
print(f'   • Финальное состояние theta: {np.rad2deg(states_history[-1][env.unwrapped.state_space.index("theta"), 0]):.4f} град')
print(f'   • Финальное состояние q: {np.rad2deg(states_history[-1][env.unwrapped.state_space.index("q"), 0]):.4f} град/с')


✅ Симуляция завершена!
   • Выполнено шагов: 500
   • Средняя награда: -0.111136
   • Финальное состояние theta: -3.9597 град
   • Финальное состояние q: -1.5308 град/с


In [8]:
# Анализ полученной награды (из последнего шага симуляции)
if len(rewards_history) > 0:
    print(f'🏆 Детальный анализ награды:')
    print(f'   • Последнее значение: {rewards_history[-1]:.6f}')
    print(f'   • Среднее значение: {np.mean(rewards_history):.6f}')
    print(f'   • Минимальное значение: {np.min(rewards_history):.6f}')
    print(f'   • Максимальное значение: {np.max(rewards_history):.6f}')
    print(f'\n📈 Интерпретация:')
    print(f'   • Награда = -|theta - theta_ref| - 0.1 * |q|')
    print(f'   • Чем выше значение (ближе к 0), тем лучше отслеживание опорного сигнала')
else:
    print(f'🏆 Детальный анализ награды:')
    print(f'   • Значение: {reward}')
    print(f'   • Тип: {type(reward)}')


🏆 Детальный анализ награды:
   • Последнее значение: -0.159049
   • Среднее значение: -0.111136
   • Минимальное значение: -0.159049
   • Максимальное значение: -0.000000

📈 Интерпретация:
   • Награда = -|theta - theta_ref| - 0.1 * |q|
   • Чем выше значение (ближе к 0), тем лучше отслеживание опорного сигнала


In [9]:
# Проверка статуса завершения эпизода
done = terminated or truncated
print('🏁 Статус симуляции:')
if done:
    print('   ✅ Эпизод завершен')
    print('   📊 Можно анализировать результаты или начать новый эпизод')
else:
    print('   🔄 Эпизод продолжается')
    print('   ➡️  Можно выполнить следующий шаг симуляции')

print(f'\n🔢 Числовое значение done: {done}')
print('   • True = эпизод завершен')
print('   • False = эпизод продолжается')

done

🏁 Статус симуляции:
   🔄 Эпизод продолжается
   ➡️  Можно выполнить следующий шаг симуляции

🔢 Числовое значение done: False
   • True = эпизод завершен
   • False = эпизод продолжается


False

---

## 🎓 Conclusion

In this example we demonstrated the basics of working with the **linear longitudinal F-16 model** in TensorAeroSpace:

### ✅ What we learned:
- 🛠️ **Creating the environment**: Initializing LinearLongitudinalF16 via gym.make()
- 🎯 **Configuring parameters**: Setting up the simulation and reference signals
- 🚀 **Executing steps**: Applying control actions in radians
- 📊 **Analyzing results**: Interpreting states, rewards, and statuses

### 📋 Important notes:
- **Model states**: Available `["theta", "alpha", "q"]` (internal state `ele` is not observable)
- **Control**: Actions in radians, range `[-0.5, 0.5]` rad (clipped to +/-25 deg)
- **Reference signal**: Format `(num_tracking_states, number_time_steps)`
- **Observations**: Shape `(len(state_space), 1)` in radians

### 🔄 Next steps:
- 🎮 **Try different control actions** to explore system behavior
- 📈 **Implement a controller** for automatic control
- 🧠 **Train a reinforcement learning agent** for optimal control
- 📋 **Explore other environments** in TensorAeroSpace (B747, X15, F4C, etc.)

### 📚 Useful resources:
- [TensorAeroSpace Documentation](https://tensoraerospace.readthedocs.io/)
- [Usage Examples](https://github.com/TensorAeroSpace/TensorAeroSpace/tree/main/examples)
- [Aircraft Flight Dynamics Theory](https://en.wikipedia.org/wiki/Aircraft_flight_dynamics)

**Good luck exploring aerospace systems! 🚀✈️**