# 🚀 Модель X-15: Экспериментальный гиперзвуковой самолёт

## 📖 Введение

Добро пожаловать в интерактивный пример работы с моделью **X-15** - легендарного экспериментального гиперзвукового самолёта! В этом notebook мы изучим:

- 🛩️ **Модель X-15**: Линейная продольная модель гиперзвукового самолёта
- 🎮 **Среда Gymnasium**: Создание и управление средой симуляции
- 📊 **Анализ данных**: Исследование состояний, управляющих воздействий и наград
- 🎯 **Система управления**: Понимание принципов управления гиперзвуковым полётом

X-15 был революционным самолётом, который достигал скоростей свыше 6 Махов и высот более 100 км, внося огромный вклад в развитие космонавтики и аэродинамики высоких скоростей.

---

## ⚙️ Настройка

Начнём с настройки рабочей среды и импорта необходимых библиотек.

### 📁 Настройка рабочей директории

Переходим в корневую директорию проекта для корректного импорта модулей:

In [1]:
# 📁 Переход в корневую директорию проекта
print('🔄 Переходим в корневую директорию...')
%cd ..
print('✅ Рабочая директория настроена!')

/app


### 📦 Импорт библиотек

Загружаем необходимые модули для работы с моделью X-15:

In [2]:
# 🎮 Основные библиотеки для работы со средой
import gym  # Фреймворк для сред обучения с подкреплением
import numpy as np  # Библиотека для численных вычислений
from tqdm import tqdm  # Прогресс-бары для циклов

# 🚀 Специфичные модули TensorAeroSpace для X-15
from tensoraerospace.envs import LinearLongitudinalX15  # Модель X-15
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp  # Утилиты времени
from tensoraerospace.signals.standart import unit_step  # Генератор ступенчатых сигналов

# 📊 Информация о загруженных модулях
print('📦 Библиотеки успешно загружены!')
print('🚀 Модель X-15 готова к использованию!')
print('🎯 Среда для гиперзвукового полёта настроена!')

### ⚙️ Параметры симуляции

Настраиваем временные параметры и опорные сигналы для симуляции гиперзвукового полёта X-15:

In [3]:
# ⏱️ Временные параметры симуляции
dt = 0.01  # Шаг дискретизации (секунды)
tp = generate_time_period(tn=20, dt=dt)  # Временной период (20 секунд)
tps = convert_tp_to_sec_tp(tp, dt=dt)  # Преобразование в секунды
number_time_steps = len(tp)  # Общее количество временных шагов

# 🎯 Создание опорного сигнала (ступенчатый сигнал)
reference_signals = np.reshape(
    unit_step(degree=5, tp=tp, time_step=10, output_rad=True), 
    [1, -1]
)

# 📊 Информация о параметрах симуляции
print('⏱️ Параметры времени:')
print(f'   📏 Шаг дискретизации: {dt} сек')
print(f'   ⏰ Общее время симуляции: {tp[-1]:.1f} сек')
print(f'   🔢 Количество шагов: {number_time_steps}')
print()
print('🎯 Опорный сигнал:')
print(f'   📐 Амплитуда ступеньки: {np.degrees(5):.1f}°')
print(f'   ⏰ Время активации: {10 * dt:.1f} сек')
print(f'   📊 Размерность сигнала: {reference_signals.shape}')

### 🚀 Создание среды X-15

Инициализируем среду симуляции гиперзвукового самолёта X-15 с заданными параметрами:

In [4]:
# 🚀 Создание среды симуляции X-15
print('🔧 Создаём среду LinearLongitudinalX15-v0...')

env = gym.make(
    'LinearLongitudinalX15-v0',
    number_time_steps=number_time_steps,
    initial_state=[[0], [0], [0], [0]],  # Начальное состояние [u, w, q, θ]
    reference_signal=reference_signals
)

# 🔄 Сброс среды в начальное состояние
initial_observation = env.reset()

# 📊 Анализ начального состояния X-15
print('✅ Среда X-15 успешно создана!')
print()
print('🛩️ Начальное состояние X-15:')
print(f'   🏃 Продольная скорость (u): {initial_observation[0]:.6f} м/с')
print(f'   ⬇️ Вертикальная скорость (w): {initial_observation[1]:.6f} м/с')
print(f'   🔄 Угловая скорость тангажа (q): {initial_observation[2]:.6f} рад/с')
print(f'   📐 Угол тангажа (θ): {initial_observation[3]:.6f} рад')
print()
print('🎯 X-15 готов к гиперзвуковому полёту!')

### 🎮 Выполнение шага симуляции

Применяем управляющее воздействие к X-15 и анализируем результат:

In [5]:
# 🎮 Применение управляющего воздействия
control_input = np.array([[1]])  # Управляющий сигнал (отклонение руля высоты)

print('🎯 Применяем управляющее воздействие к X-15...')
print(f'🕹️ Управляющий сигнал: {control_input[0][0]:.3f}')
print('⚡ Выполняем шаг симуляции...')

# 🚀 Выполнение одного шага симуляции
observation, reward, done, info = env.step(control_input)

# 📊 Анализ результатов шага
print('✅ Шаг симуляции выполнен!')
print()
print('📈 Результаты симуляции:')
print(f'   🎯 Управляющий сигнал: {control_input[0][0]:.3f}')
print(f'   🏁 Завершение эпизода: {done}')
print(f'   🎁 Награда: {reward[0]:.2e}')
print(f'   📊 Размерность наблюдения: {observation.shape}')
print()
print('🛩️ X-15 успешно отреагировал на управление!')

### 🔍 Анализ внутренних данных модели

Исследуем историю управляющих воздействий, сохранённую в модели X-15:

In [6]:
# 🔍 Получение истории управляющих воздействий
input_history = env.model.store_input

# 📊 Анализ истории входных сигналов
print('🔍 Анализ истории управляющих воздействий X-15:')
print(f'📏 Размерность истории: {input_history.shape}')
print(f'🔢 Количество ненулевых входов: {np.count_nonzero(input_history)}')
print(f'🎯 Первые 5 значений: {input_history[0, :5]}')
print(f'📈 Максимальное значение: {np.max(input_history):.3f}')
print(f'📉 Минимальное значение: {np.min(input_history):.3f}')
print()
print('💡 История показывает применённые управляющие сигналы')
print('   к рулю высоты X-15 на каждом временном шаге')

input_history

array([[1., 0., 0., ..., 0., 0., 0.]])

### 📊 Анализ состояния X-15

Исследуем текущее состояние гиперзвукового самолёта после применения управляющего воздействия:

In [7]:
# 📊 Анализ текущего состояния X-15
current_observation = observation

# 🛩️ Детальный разбор состояния
print('📊 Анализ состояния X-15 после управляющего воздействия:')
print(f'📏 Размерность наблюдения: {current_observation.shape}')
print()

# Примечание: В данной модели наблюдение содержит только часть состояния
print('🔍 Компоненты наблюдения:')
for i, value in enumerate(current_observation):
    print(f'   📈 Компонент {i+1}: {value[0]:.2e}')

print()
print('💡 Наблюдение показывает изменения в динамике X-15')
print('   после применения управляющего сигнала к рулю высоты')
print('🚀 Значения в научной нотации указывают на малые изменения')
print('   что характерно для начальных моментов управления')

current_observation

array([[-5.91396593e-09],
       [-1.16165197e-06]])

### 🏆 Анализ системы наград

Исследуем награду, полученную X-15 за выполненное управляющее воздействие:

In [8]:
# 🏆 Анализ системы наград X-15
current_reward = reward[0]

# 🔍 Интерпретация награды
print('🏆 Анализ награды за управление X-15:')
print(f'🎯 Значение награды: {current_reward:.2e}')
print(f'📊 Порядок величины: {np.log10(abs(current_reward)):.1f}')
print()

# 💡 Интерпретация результата
if current_reward > 0:
    print('✅ Положительная награда - хорошее управление!')
    print('🚀 X-15 движется в правильном направлении')
    print('📈 Система управления работает эффективно')
elif current_reward == 0:
    print('⚖️ Нейтральная награда - стабильное состояние')
    print('🛩️ X-15 поддерживает текущий режим полёта')
else:
    print('❌ Отрицательная награда - требуется коррекция')
    print('🔧 Необходимо улучшить управляющие воздействия')

print()
print('💡 Интерпретация для X-15:')
print(f'   Награда {current_reward:.2e} отражает качество')
print('   отслеживания опорного сигнала гиперзвуковым самолётом')
print('🎯 Малое значение характерно для начальных этапов управления')

reward

array([5.91396593e-09])

## 🎯 Заключение и следующие шаги

### 📚 Что мы изучили:

1. **🚀 Модель X-15** - экспериментальный гиперзвуковой самолёт
2. **🏋️ Среда Gymnasium** - интерфейс для обучения с подкреплением
3. **📊 Анализ состояния** - 4-мерный вектор наблюдений (скорости, угловая скорость, угол тангажа)
4. **🎮 Система управления** - одномерные управляющие воздействия
5. **🏆 Система наград** - оценка качества управления
6. **📈 Мониторинг** - отслеживание внутренних данных модели

### 🚀 Следующие шаги:

1. **🤖 Обучение RL-агента** - создание интеллектуального пилота
2. **⚙️ Настройка параметров** - оптимизация симуляции
3. **🛩️ Сложные траектории** - тестирование различных манёвров
4. **📊 Визуализация** - графики состояний и управления
5. **🔬 Анализ производительности** - метрики качества управления

### 📖 Полезные ресурсы:

- [Reinforcement Learning: An Introduction](http://incompleteideas.net/book/the-book-2nd.html) - классический учебник по RL
- [Gymnasium Documentation](https://gymnasium.farama.org/) - документация по средам RL
- [TensorAeroSpace](https://github.com/TensorAeroSpace/TensorAeroSpace) - библиотека аэрокосмических сред

---

🎉 **Поздравляем!** Вы успешно освоили основы работы с гиперзвуковым самолётом X-15 в TensorAeroSpace. 
Используйте этот notebook как отправную точку для ваших исследований в области управления летательными аппаратами!