# 🚀 Example: Working with the ELV Rocket Model

This notebook demonstrates the usage of the linear longitudinal model of an Expendable Launch Vehicle (ELV) in the TensorAeroSpace environment.

## 📋 What we will do:
1. Import the required libraries
2. Configure time parameters and the reference signal
3. Create and initialize the rocket environment
4. Execute a simulation step with a control action
5. Analyze the results and the internal model state

## 📚 Importing Libraries

Loading all necessary modules for working with the launch vehicle model:

In [1]:
# Основные библиотеки
import gymnasium as gym
import numpy as np
from tqdm import tqdm

# Модули TensorAeroSpace для работы с ракетой
from tensoraerospace.envs import LinearLongitudinalELVRocket
from tensoraerospace.utils import generate_time_period, convert_tp_to_sec_tp
from tensoraerospace.signals.standart import unit_step

## ⚙️ Simulation Parameters Setup

Defining time parameters and creating a step reference signal for rocket control:

In [2]:
# Параметры дискретизации
dt = 0.01  # Шаг дискретизации (секунды)

# Генерация временного периода для симуляции
tp = generate_time_period(tn=20, dt=dt)  # 20 секунд полета ракеты
tps = convert_tp_to_sec_tp(tp, dt=dt)    # Преобразование в секунды
number_time_steps = len(tp)             # Общее количество временных шагов

# Создание ступенчатого опорного сигнала
# Команда на изменение траектории подается на 10-й секунде полета
reference_signals = np.reshape(
    unit_step(degree=5, tp=tp, time_step=10, output_rad=True), 
    [1, -1]
)

print(f'🚀 Параметры симуляции ракеты:')
print(f'   • Время полета: {tp[-1]:.1f} сек')
print(f'   • Шаг дискретизации: {dt} сек')
print(f'   • Количество шагов: {number_time_steps}')
print(f'   • Команда на маневр: {10} сек')

🚀 Параметры симуляции ракеты:
   • Время полета: 2002.0 сек
   • Шаг дискретизации: 0.01 сек
   • Количество шагов: 2002
   • Команда на маневр: 10 сек


## 🛸 Creating and Initializing the Rocket Environment

Creating the ELV Rocket environment with the specified parameters and performing initialization:

In [3]:
# Создание среды ракеты-носителя
env = gym.make(
    'LinearLongitudinalELVRocket-v0',
    number_time_steps=number_time_steps,     # Количество временных шагов
    initial_state=[[0],[0],[0]],             # Начальное состояние [скорость, угол, угловая_скорость]
    reference_signal=reference_signals       # Опорный сигнал для управления
)

# Инициализация среды и получение начального состояния
initial_state, info = env.reset()

print(f'✅ Среда ракеты успешно создана!')
print(f'🎯 Начальное состояние: {initial_state.flatten()}')
print(f'📊 Размерность пространства состояний: {env.observation_space.shape}')
print(f'🎮 Размерность пространства действий: {env.action_space.shape}')

# Возвращаем результат инициализации
(initial_state, info)

✅ Среда ракеты успешно создана!
🎯 Начальное состояние: [0. 0. 0.]
📊 Размерность пространства состояний: (3,)
🎮 Размерность пространства действий: (1,)


(array([0., 0., 0.], dtype=float32), {})

## 🎮 Executing a Control Action

Applying an engine control command to the rocket and observing the state change:

In [4]:
# Применение управляющего воздействия
control_command = np.array([[1]])  # Команда управления (тяга двигателей)

# Выполнение одного шага симуляции
state, reward, terminated, truncated, info = env.step(control_command)

print(f'🚀 Управляющая команда: {control_command.flatten()[0]}')
print(f'📈 Новое состояние ракеты: {state.flatten()}')
print(f'🏆 Полученная награда: {reward}')
print(f'🔚 Миссия завершена: {terminated}')
print(f'⏰ Симуляция прервана: {truncated}')
print(f'ℹ️ Дополнительная информация: {info}')

🚀 Управляющая команда: 1
📈 Новое состояние ракеты: [5.61887791e-02 1.99152908e-02 9.27699394e-05]
🏆 Полученная награда: [9.27699394e-05]
🔚 Миссия завершена: False
⏰ Симуляция прервана: False
ℹ️ Дополнительная информация: {}


/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/Users/asmazaev/TensorAeroSpace-Origin/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:246: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(


## 📊 Flight Results Analysis

Examining the control command history and reference signals:

In [5]:
# Просмотр истории управляющих команд
print(f'📝 История команд управления двигателями:')
print(f'   • Первые команды: {env.unwrapped.model.store_input[0][:5]}')
print(f'   • Общее количество команд: {env.unwrapped.model.store_input.shape[1]}')

# Полная история команд
env.unwrapped.model.store_input

📝 История команд управления двигателями:
   • Первые команды: [0.43633231 0.         0.         0.         0.        ]
   • Общее количество команд: 2002


array([[0.43633231, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [6]:
# Анализ опорного сигнала
print(f'🎯 Анализ опорного сигнала:')
print(f'   • Текущее значение (шаг 1): {env.unwrapped.reference_signal[0][1]}')
print(f'   • Форма сигнала: {env.unwrapped.reference_signal.shape}')
print(f'   • Тип сигнала: Ступенчатый (активация на 10-й секунде)')

# Значение опорного сигнала на втором временном шаге
env.unwrapped.reference_signal[0][1]

🎯 Анализ опорного сигнала:
   • Текущее значение (шаг 1): 0.0
   • Форма сигнала: (1, 2002)
   • Тип сигнала: Ступенчатый (активация на 10-й секунде)


0.0

In [7]:
# Детальный анализ системы награды
print(f'🏆 Анализ системы награды:')
print(f'   • Значение награды: {reward}')
print(f'   • Тип данных: {type(reward)}')
print(f'   • Форма массива: {reward.shape if hasattr(reward, "shape") else "скаляр"}')
print(f'   • Интерпретация: Мера качества отслеживания опорной траектории')
print(f'   • Цель: Минимизация отклонения от заданного маршрута')

# Возвращаем значение награды
reward

🏆 Анализ системы награды:
   • Значение награды: [9.27699394e-05]
   • Тип данных: <class 'numpy.ndarray'>
   • Форма массива: (1,)
   • Интерпретация: Мера качества отслеживания опорной траектории
   • Цель: Минимизация отклонения от заданного маршрута


array([9.27699394e-05])

## 🎉 Conclusion

In this example we successfully demonstrated working with the launch vehicle model:

✅ **Created the ELV Rocket environment** with correct parameters
✅ **Configured time parameters** and the reference signal for control
✅ **Executed a flight simulation** with control commands
✅ **Analyzed the results** and the internal model state

### 🚀 Rocket model features:
- **3 states**: Velocity, trajectory inclination angle, angular velocity
- **Control**: Engine thrust commands
- **Goal**: Precisely following the given flight trajectory

### 📊 Reward system:
- **Principle**: Evaluating the quality of reference signal tracking
- **Optimization**: Minimizing deviation from the given route
- **Application**: Training the rocket autopilot

### 🎯 Practical applications:
This model can be used for:
- Developing automatic rocket control systems
- Training reinforcement learning algorithms for space missions
- Testing trajectory control strategies
- Simulating various flight scenarios

The model is ready for use in complex spacecraft control tasks! 🌌